name: 10
timestamp: 1601289690
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1551356003
positions:
  showcase-bottom: 'Showcase Bottom'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  feature-d: 'Feature D'
  feature-e: 'Feature E'
  feature-f: 'Feature F'
  mainbottom-title: 'Mainbottom Title'
  mainbottom: Mainbottom
  subfeature-a: 'Subfeature A'
  subfeature-b: 'Subfeature B'
  subfeature-c: 'Subfeature C'
  subfeature-d: 'Subfeature D'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  extension-d: 'Extension D'
  extension-e: 'Extension E'
  extension-f: 'Extension F'
  announcement: 'Module Position'
  logo: 'Module Position'
  top: Top
  navigation: Navigation
  mobile-links: 'Mobile Links'
  showcase: Showcase
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  footer-d: 'Footer D'
  copyright-a: 'Copyright A'
  copyright-b: 'Copyright B'
  mobile-menu-container: 'Module Position'
sections:
  top: Top
  mobile-links: Mobile-links
  showcase: Showcase
  showcase-bottom: Showcase-bottom
  feature: Feature
  mainbottom: Mainbottom
  subfeature: Subfeature
  extension: Extension
  copyright: Copyright
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-7923: 'Showcase Bottom'
    position-position-2390: 'Feature A'
    position-position-9495: 'Feature B'
    position-position-4694: 'Feature C'
    position-position-5050: 'Feature D'
    position-position-6078: 'Feature E'
    position-position-3499: 'Feature F'
    position-position-2510: 'Mainbottom Title'
    position-position-1197: Mainbottom
    position-position-9129: 'Subfeature A'
    position-position-4438: 'Subfeature B'
    position-position-4678: 'Subfeature C'
    position-position-7456: 'Subfeature D'
    position-position-4750: 'Extension A'
    position-position-8023: 'Extension B'
    position-position-5238: 'Extension C'
    position-position-8435: 'Extension D'
    position-position-8244: 'Extension E'
    position-position-6462: 'Extension F'
    position-position-1314: 'Module Position'
    position-position-7747: 'Module Position'
    position-position-8690: Top
    position-position-8290: Navigation
    position-position-9371: 'Mobile Links'
    position-position-9308: Showcase
    position-position-4888: 'Footer A'
    position-position-6544: 'Footer B'
    position-position-6336: 'Footer C'
    position-position-5972: 'Footer D'
    position-position-9537: 'Copyright A'
    position-position-9773: 'Copyright B'
    position-position-6169: 'Module Position'
  messages:
    system-messages-4872: 'System Messages'
inherit:
  default:
    top: top
    header: header
    mobile-links: mobile-links
    showcase: showcase
    footer: footer
    copyright: copyright
    offcanvas: offcanvas
    position-position-1314: position-position-5167
    position-position-7747: position-position-8842
    position-position-8690: position-position-5208
    position-position-8290: position-position-1963
    position-position-9371: position-position-4289
    position-position-9308: position-position-1418
    position-position-4888: position-footer
    position-position-6544: position-position-7699
    position-position-6336: position-position-6812
    position-position-5972: position-position-8076
    position-position-9537: position-position-5533
    position-position-9773: position-position-5669
    position-position-6169: position-position-5845
