CREATE TABLE IF NOT EXISTS `#__eckoh_hubproduct` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`productname` VARCHAR(255)  NOT NULL ,
`visibleproductname` VARCHAR(255)  NOT NULL ,
`subtitle` VARCHAR(255)  NOT NULL ,
`language` VARCHAR(5)  NOT NULL ,
`imageorvideo` TEXT NOT NULL ,
`introparagraph` TEXT NOT NULL ,
`topfeatureboxes` TEXT NOT NULL ,
`featurearea` TEXT NOT NULL ,
`featureimage` TEXT NOT NULL ,
`middlefeatureboxes` TEXT NOT NULL ,
`calltoactiontext` TEXT NOT NULL ,
`calltoactionbutton` VARCHAR(255)  NOT NULL ,
`calltoactionbuttontext` VARCHAR(255)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__eckohproducts_level2plus` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`productname` VARCHAR(255)  NOT NULL ,
`visibleproductname` VARCHAR(255)  NOT NULL ,
`subtitle` VARCHAR(255)  NOT NULL ,
`language` VARCHAR(5)  NOT NULL ,
`imageorvideo` TEXT NOT NULL ,
`introparagraph` TEXT NOT NULL ,
`topfeatures` TEXT NOT NULL ,
`featurearea` TEXT NOT NULL ,
`featureimage` TEXT NOT NULL ,
`minicalltoactionboxtext` TEXT NOT NULL ,
`minicalltoactionurl` VARCHAR(255)  NOT NULL ,
`minicalltoactionbuttontext` VARCHAR(255)  NOT NULL ,
`casestudytext` TEXT NOT NULL ,
`casestudyimage` VARCHAR(255)  NOT NULL ,
`featurearea2` TEXT NOT NULL ,
`featureimage2` TEXT NOT NULL ,
`calltoactiontext` TEXT NOT NULL ,
`calltoactionurl` VARCHAR(255)  NOT NULL ,
`calltoactionbuttontext` VARCHAR(255)  NOT NULL ,
`bottomboxes` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__eckohproducts_level2or3` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`productname` VARCHAR(255)  NOT NULL ,
`visibleproductname` VARCHAR(255)  NOT NULL ,
`subtitle` VARCHAR(255)  NOT NULL ,
`language` VARCHAR(5)  NOT NULL ,
`imageorvideo` TEXT NOT NULL ,
`introparagraph` TEXT NOT NULL ,
`featurearea` TEXT NOT NULL ,
`featureimage` TEXT NOT NULL ,
`minicalltoactionboxtext` TEXT NOT NULL ,
`minicalltoactionurl` VARCHAR(255)  NOT NULL ,
`minicalltoactionbuttontext` VARCHAR(255)  NOT NULL ,
`casestudytext` TEXT NOT NULL ,
`casestudyimage` VARCHAR(255)  NOT NULL ,
`featurearea2` TEXT NOT NULL ,
`featureimage2` TEXT NOT NULL ,
`calltoactiontext` TEXT NOT NULL ,
`calltoactionurl` VARCHAR(255)  NOT NULL ,
`calltoactionbuttontext` VARCHAR(255)  NOT NULL ,
`bottomboxes` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

