version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1537970621
layout:
  /main/:
    -
      - system-messages-6697
    -
      - system-content-2071
structure:
  main:
    attributes:
      boxed: ''
